### ISSUE TITLE
Suggestion: format constants that match "time"

### ISSUE THREAD

**Issue by muir** [phuslu/fasttime#2]
To make this an easy drop-in replacement for `time`'s `Format()`, it would be great to predefine format strings.

At least equivalents to `time.RFC3339`

**Comment by phuslu** [comment]
Thanks, I added https://github.com/phuslu/fasttime/commit/64c4ecdd6616b659ee401a0b4c14e32471d8fd32

But the RFC3339 zone "Z07:00" cannot be represented in strftime layout, which only support "Z0700"

**Comment by phuslu** [comment]
Added a '%^z' to support RFC3339, see https://github.com/phuslu/fasttime/commit/77fa9bd3538af54941e20f14ea2d2aed51c8598d

I'm not sure `%^z` , `%_z`, or `%#z` which is better, do you have any ideas/suggestions? thanks.

**Comment by phuslu** [comment]
Finally I choose `%:z` same as https://github.com/itchyny/timefmt-go
